version: '3.8'
services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run src/dashboard/app.py

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri /mlflow/mlruns --host 0.0.0.0

  prefect:
    image: prefecthq/prefect:2-latest
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    command: prefect server start
